# Generated by Django 3.2.5 on 2021-08-03 17:52

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.MyUserManager()),
            ],
        ),
    ]
