# Generated by Django 3.2.5 on 2021-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='was_read',
            field=models.BooleanField(default=False, help_text='Please if Read this Message Select the Checkbox to Mark as Read', verbose_name='Was Read'),
        ),
        migrations.AlterField(
            model_name='message',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create TimeStamp'),
        ),
        migrations.AlterField(
            model_name='message',
            name='modify_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify TimeStamp'),
        ),
    ]
