# Generated by Django 3.2.5 on 2021-08-21 15:48

import core.models
import core.validators
import customer.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('photo', models.FileField(blank=True, default='Unknown.jpg', help_text='Please Upload Uour Image if You Wish.', upload_to='customer/customers/', verbose_name='Profile Picture')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], default=None, help_text='Please Select Your Gender if You Wish.', max_length=1, null=True, verbose_name='Gender')),
                ('birth_day', models.DateField(blank=True, default=None, help_text='Please Enter Your Birth Day if You Wish.', null=True, validators=[customer.validators.birthday_validator], verbose_name='Birth Day')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create TimeStamp')),
                ('modify_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modify TimeStamp')),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(help_text="Please Enter Your Address' Name", max_length=50, verbose_name="Address' Name")),
                ('zip_code', models.CharField(help_text='Please Enter Your Zip Code', max_length=10, unique=True, validators=[core.validators.Validators.check_postal_code], verbose_name='Zip Code')),
                ('country', models.CharField(default='ایران', help_text='Please Enter Your Country(By Default Iran is Considered).', max_length=10, verbose_name='Country')),
                ('province', models.CharField(help_text='Please Enter Your Province For Example Tehran or Alborz or ...', max_length=10, verbose_name='Province')),
                ('city', models.CharField(help_text='Please Enter Your City For Example Tehran or Karaj or ...', max_length=10, verbose_name='City')),
                ('rest', models.TextField(help_text='Please Enter the Rest of Your Address Accurately', verbose_name='Continue Address(Street and Alley)')),
                ('lat', models.FloatField(help_text='Please Enter Your Address Latitude', verbose_name='Latitude')),
                ('lng', models.FloatField(help_text='Please Enter Your Address Longitude', verbose_name='Longitude')),
                ('customer', models.ForeignKey(help_text='Please Select Customer Owner this Address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'unique_together': {('lat', 'lng')},
            },
        ),
    ]
