# Generated by Django 3.2.5 on 2021-08-03 22:38

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutomer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('photo', models.FileField(blank=True, default='Unknown.jpg', help_text='Please Upload Uour Image if You Wish.', upload_to='customer/customers/', verbose_name='Profile Picture')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], default=None, help_text='Please Select Your Gender if You Wish.', max_length=1, null=True, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, default=None, help_text='Please Enter Your Birth Day if You Wish.', null=True, verbose_name='Birth Day')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Cutomers',
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.MyUserManager()),
            ],
        ),
    ]
