# Generated by Django 3.2.5 on 2021-08-08 22:17

import customer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_day',
            field=models.DateField(blank=True, default=None, help_text='Please Enter Your Birth Day if You Wish.', null=True, validators=[customer.validators.birthday_validator], verbose_name='Birth Day'),
        ),
    ]
