# Generated by Django 3.2.5 on 2021-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create TimeStamp'),
        ),
        migrations.AlterField(
            model_name='address',
            name='modify_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify TimeStamp'),
        ),
    ]
