# Generated by Django 3.2.5 on 2021-08-04 10:07

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='', help_text='Please Enter Your City For Example Tehran or Karaj or ...', max_length=10, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='ایران', help_text='Please Enter Your Country(By Default Iran is Considered).', max_length=10, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(default='', help_text='Please Select Customer Owner this Address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer.customer', verbose_name='Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='', help_text='Please Enter Your Postal Code', max_length=10, unique=True, validators=[core.validators.Validators.check_postal_code], verbose_name='Postal Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='', help_text='Please Enter Your Province For Example Tehran or Alborz or ...', max_length=10, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='rest',
            field=models.TextField(default='', help_text='Please Enter the Rest of Your Address Accurately', verbose_name='Continue Address(Street and Alley)'),
            preserve_default=False,
        ),
    ]
