# Generated by Django 3.2.5 on 2021-07-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('title_en', models.CharField(help_text='Please Enter the Title of the Name in English', max_length=100, unique=True, verbose_name='English Title')),
                ('title_fa', models.CharField(help_text='Please Enter the Title of the Name in Persian', max_length=100, unique=True, verbose_name='Persian Title')),
                ('root', models.ForeignKey(blank=True, help_text='Please Select the Main Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Main Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
