# Generated by Django 3.2.5 on 2021-07-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('title_en', models.CharField(help_text='Please Enter the Title of the Name in English', max_length=100, unique=True, verbose_name='English Title')),
                ('title_fa', models.CharField(help_text='Please Enter the Title of the Name in Persian', max_length=100, unique=True, verbose_name='Persian Title')),
                ('slug', models.SlugField(help_text='Please Type Your Slug', verbose_name='Slug')),
                ('logo', models.FileField(default='product/brands/Unknown.jpg', help_text='Please Upload the Logo Icon of Brand', upload_to='product/brands/', verbose_name='Logo')),
                ('link', models.URLField(blank=True, default=None, help_text='Please Enter Your Website Address', null=True, verbose_name='Website Address')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', help_text='Please Type Your Slug', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
