# Generated by Django 3.2.5 on 2021-07-27 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210727_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.URLField(blank=True, default=None, help_text='Please Enter Your Website Address', null=True, validators=[django.core.validators.URLValidator], verbose_name='Website Address'),
        ),
    ]
