# Generated by Django 3.2.5 on 2021-07-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_brand_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, default='product/brands/Unknown.jpg', help_text='Please Upload the Logo Icon of Brand', upload_to='product/brands/', verbose_name='Logo'),
        ),
    ]
