# Generated by Django 3.2.5 on 2021-07-28 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('title_en', models.CharField(help_text='Please Enter the Title of the Name in English', max_length=100, unique=True, verbose_name='English Title')),
                ('title_fa', models.CharField(help_text='Please Enter the Title of the Name in Persian', max_length=100, unique=True, verbose_name='Persian Title')),
                ('slug', models.SlugField(help_text='Please Type Your Slug', verbose_name='Slug')),
                ('unit', models.CharField(choices=[('P', 'Percent'), ('T', 'Toman')], help_text='Please Select the Discount Unit', max_length=1, verbose_name='Unit')),
                ('amount', models.PositiveBigIntegerField(default=0, help_text='Please Enter Discount Amount', verbose_name='Discount Amount')),
                ('roof', models.PositiveBigIntegerField(blank=True, default=None, help_text='Please Enter Discount Ceiling(Optional)', null=True, verbose_name='Discount Ceiling')),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Please Select the Start Date of the Discount', null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, default=None, help_text='Please Select the End Date of the Discount', null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
    ]
