# Generated by Django 3.2.5 on 2021-07-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('title_en', models.CharField(help_text='Please Enter the Title of the Name in English', max_length=100, unique=True, verbose_name='English Title')),
                ('title_fa', models.CharField(help_text='Please Enter the Title of the Name in Persian', max_length=100, unique=True, verbose_name='Persian Title')),
                ('slug', models.SlugField(help_text='Please Type Your Slug', verbose_name='Slug')),
                ('image', models.FileField(blank=True, default='product/products/Unknown.jpg', help_text='Please Upload a Picture of the Product Item', upload_to='product/products/', verbose_name='Picture')),
                ('price', models.PositiveBigIntegerField(help_text='Please Enter the Price of Product Item without Apply Discount', verbose_name='Price')),
                ('inventory', models.PositiveBigIntegerField(help_text='Please Enter the Number of this Product Item into the Stock', verbose_name='Number of Inventory')),
                ('brand', models.ForeignKey(help_text='Please Select the Brand of the Product Item', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(help_text='Please Select the Category of the Product Item', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Category')),
                ('discount', models.ForeignKey(blank=True, default=None, help_text='Please Select the Type of Discount if Available', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.discount', verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
