# Generated by Django 3.2.5 on 2021-07-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, default='Unknown.jpg', help_text='Please Upload the Logo Icon of Brand', upload_to='product/brands/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='Unknown.jpg', help_text='Please Upload a Picture of the Product Item', upload_to='product/products/', verbose_name='Picture'),
        ),
    ]
