# Generated by Django 3.2.5 on 2021-08-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210801_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='properties',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
