# Generated by Django 3.2.5 on 2021-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
