# Generated by Django 3.2.5 on 2021-08-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='root',
            field=models.ForeignKey(blank=True, default=None, help_text='Please Select the Main Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='product.category', verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, help_text='Please Select the Type of Discount if Available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.discount', verbose_name='Discount'),
        ),
    ]
